### ISSUE TITLE
Exploring Remote Sensing data for phenology

### ISSUE THREAD

**Issue by khzadeh** [phenology/springtime#3] opened 2022-09-26 13:53 UTC
I want to overview the available sources including the Google Earth Engine for making the phenological exploratory variables.
I want to check the possibility of getting data from primary sources.

**Comment by SarahAlidoost** [comment] 2022-10-25 14:36
Other tools to explore RS data:

- https://earthexplorer.usgs.gov/ 
- https://worldview.earthdata.nasa.gov/
- https://www.earthdata.nasa.gov/learn/find-data

and this might be of interest https://www.earthdatascience.org/tutorials/

**Comment by Peter9192** [comment] 2022-10-27 10:33
For reference: https://carpentries-incubator.github.io/geospatial-python/05-access-data/index.html tutorial on accessing sat data with stac

**Comment by Peter9192** [comment] 2022-10-27 11:00
Earth search: https://www.element84.com/earth-search/
Appears: https://appeears.earthdatacloud.nasa.gov/
Copernicus open access hub: https://scihub.copernicus.eu/

**Comment by Peter9192** [comment] 2022-10-27 11:58
OSGeo also worth checking out, e.g.: https://www.osgeo.org/choose-a-project/analysis-and-processing/raster-processing/

**Comment by khzadeh** [comment] 2022-11-07 16:11
Programmatic interface to the ‘MODIS Land Products Subsets’ web services. Allows for easy downloads of ‘MODIS’ time series directly to your R workspace or your computer: https://github.com/ropensci/MODISTools

**Comment by Peter9192** [comment] 2022-11-16 09:44
> Programmatic interface to the ‘MODIS Land Products Subsets’ web services. Allows for easy downloads of ‘MODIS’ time series directly to your R workspace or your computer: https://github.com/ropensci/MODISTools

This looks nice! From the looks of it you can easily download either a point or a full region. I wonder if it is also possible to download a subset of a region. 

From [their documentation](https://docs.ropensci.org/MODISTools/) they refer to the Modis land subset web services: https://modis.ornl.gov/data/modis_webservice.html. This is a simple REST API that can also be accessed through python. Their example: https://github.com/ornldaac/modis_restservice_qc_filter_Python/blob/master/modis_restservice_qc_filter_Python.ipynb.

**Comment by Peter9192** [comment] 2022-11-17 13:22
This tool was just presented during the symposium: https://openeo.org/

It seems to be able to download from GEE and other sources with a very nice and uniform APIs

**Comment by Peter9192** [comment] 2023-02-07 14:50
Closing this as we're past the exploratory phase. Some final notes:

- OpenEO seems nice but not it's implementation by data providers is not mature enough to be used reliably
- There are several existing tools for most repositories, each with their own quirks. There seems to be no easy way to make everything more uniform. Thus, we'll use existing tools and only develop a small framework around them to use them in a slightly more robust/reproducible manner.

**Closed by Peter9192** 2023-02-07 14:50 UTC
